#!/usr/bin/perl -w

# Generate vectors.asm, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print "; Generated by vectors.pl - do not edit\n";
print "; handlers\n";
print "bits 32\n";
print "extern _alltraps\n";
for(my $i = 0; $i < 256; $i++){
    print "global vector$i\n";
    print "vector$i:\n";
    if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
        print "  push	dword 0\n";
    }
    print "  push	dword $i\n";
    print "  jmp	_alltraps\n";
}

print "\n; vector table\n";
print "section .data\n";
print "global _vectors\n";
print "_vectors:\n";
for(my $i = 0; $i < 256; $i++){
    print "  dd vector$i\n";
}

# sample output:
#   ; handlers
#   extern _alltraps
#   global vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp _alltraps
#   ...
#   
#   ; vector table
#   section .data
#   global _vectors
#   _vectors:
#     dd vector0
#     dd vector1
#     dd vector2
#   ...

